#!/usr/bin/env python3

from argparse import ArgumentParser
from pathlib import Path
from argcomplete import autocomplete

prog = Path(__file__)
parser = ArgumentParser(prog=prog.name, description='Decrypting Filter')
parser.add_argument('key', type=str.encode, help="decryption key")
autocomplete(parser)
args = parser.parse_args()

from sys import stdin, stdout, stderr, exit
from cryptography.fernet import Fernet, InvalidToken

try:
    fernet = Fernet(args.key)
except ValueError as e:
    print(e, file=stderr)
    exit(1)
data = stdin.buffer.read()
try:
    decrypted = fernet.decrypt(data)
except InvalidToken:
    print(f'{prog.name}: bad key', file=stderr)
    exit(4)
stdout.buffer.write(decrypted)
