#!/usr/bin/env python3

from argparse import ArgumentParser, ArgumentTypeError
from argcomplete import autocomplete
import string
from pathlib import Path


def positive_int(text):
    try:
        i = int(text)
        if i <= 0:
            raise ValueError('not positive')
        return i
    except ValueError:
        raise ArgumentTypeError(f"not a positive integer: {text}")


not_whitespace = ''.join(set(string.printable) - set(string.whitespace))

letter_set_names = [
    attr
    for attr, value in vars(string).items()
    if not attr.startswith('_') and isinstance(value, str)
]
sources = ', '.join(letter_set_names)

app = Path(__file__)
parser = ArgumentParser(
    prog=app.name,
    description='Generate Random Characters',
)
parser.add_argument('count', type=positive_int,
    help='how many random characters to generate')
parser.add_argument('--sources', '-s', nargs='+', default=not_whitespace,
    help=f'candidate sources for letters; can either be any of {sources} or '
         'some arbitrary characters; default printable except whitespace')
autocomplete(parser)
args = parser.parse_args()


import secrets
from sys import stdout, stderr, exit

try:
    chars = ''.join(set(''.join(
        getattr(string, s, s)
        for s in args.sources
    )))
    print(
        ''.join(secrets.choice(chars) for _ in range(args.count)),
        end=None if stdout.isatty() else '',
    )
except IndexError as e:
    print(e, file=stderr)
    exit(1)
